### PR TITLE
refactor: remove internal bluebird usage & upgrade packages

### PR DESCRIPTION
**Pull request by aaarichter**
- [x] **refactor:** remove bluebird and lodash
- [x] **chore:** upgrade packages
- [x] **docs:** update README installation & example code

### CODE REVIEW

**Comment by dbushong** [comment]
Are we actually dropping node 8 support?  I don't recall any 10-specific changes in there.

The only other potential breaking change is having our promises not be Bluebirdy - but I only saw that change in the snapshot bit - is that exposed all the way out as a public API?  If so, we should mention that as the breaking change.

**Comment by aaarichter** [comment]
> Are we actually dropping node 8 support?

Indirectly with the package upgrades. 

> is that exposed all the way out as a public API

not this one. it is used used within a `afterAll` hook

Just in general - when any testium promise chain command is internally based on bluebird but it is not mentioned in the documentation, is it a breaking change or not? 
e.g would we assume `browser.bluebirdyAction().spread(...)` ?

**Comment by dbushong** [comment]
>> Are we actually dropping node 8 support?

> Indirectly with the package upgrades.

None of the `dependencies` upgrades are notable; just because we're testing on 10+ doesn't require a breaking change.

Re: bluebird chain: exactly:  if we return a Promise which a consuming app or lib might have expected to be bluebirdy, and we stop having it be bluebirdy, it's a breaking change.  If we only use it internally and it never trickles all the way out, we're fine.

**Comment by aaarichter** [comment]
> None of the dependencies upgrades are notable; just because we're testing on 10+ doesn't require a breaking change.

you are right. I had the concern that not testing with node8 is irresponsible but eslint catches unsupported language features based on the package.json engine setting. So we are good as you say.

> Re: bluebird chain: exactly: if we return a Promise which a consuming app or lib might have expected to be bluebirdy, and we stop having it be bluebirdy, it's a breaking change. If we only use it internally and it never trickles all the way out, we're fine.

confirmed. this snapshot function is only used internally and not exposed

---

@dbushong I reverted node engine settings to 8.3. please have another look

**Pull request closed without merging**
